/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <CBUS_SCLK_aliases.h>
#include <CBUS_SCLK.h>
#include <USBFS.h>
#include <USBFS_audio.h>
#include <USBFS_cdc.h>
#include <USBFS_hid.h>
#include <USBFS_midi.h>
#include <USBFS_pvt.h>
#include <WAITCLK.h>
#include <UART_1.h>
#include <LEDControl.h>
#include <CBusAddrRegL.h>
#include <CBUSControl_ctrlapi.h>
#include <CBusAddrRegH.h>
#include <CBusAddrRegU.h>
#include <TickTimer.h>
#include <timer_clock.h>
#include <ChipWaitTimer7_api.h>
#include <ChipWaitTimer6_api.h>
#include <ChipWaitTimer2_api.h>
#include <ChipWaitTimer5_api.h>
#include <ChipWaitTimer1_api.h>
#include <ChipWaitTimer4_api.h>
#include <ChipWaitTimer0_api.h>
#include <ChipWaitTimer3_api.h>
#include <TickTimerISR.h>
#include <BUSCLK.h>
#include <DigitalReset.h>
#include <EEPROM.h>
#include <DIPSW_aliases.h>
#include <DipSwReadReg.h>
#include <Bootloadable_1.h>
#include <USBFS_Dm_aliases.h>
#include <USBFS_Dm.h>
#include <USBFS_Dp_aliases.h>
#include <USBFS_Dp.h>
#include <UART_1_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

